---
- name: "Generate Kubernetes resource yamls"
  template:
    src: "../templates/{{ template }}-{{ item }}.yml"
    dest: "{{ yamls }}/{{ name }}-{{ item }}.yml"
  with_items: "{{ files }}"
  when: files is defined

- name: "Generate Kubernetes resource yamls using a list"
  template:
    src: "../templates/{{ template }}-{{ file }}.yml"
    dest: "{{ yamls }}/{{ naming.prefix }}-{{ item[naming.prop] }}-{{ file }}.yml"
  with_items: "{{ with_list }}" 
  when: with_list is defined and naming is defined
