---
- name: "Generate {{ yamls }}/{{ name }}-{{ item }}.yml"
  template:
    src: "../templates/{{ template }}-{{ item }}.yml"
    dest: "{{ yamls }}/{{ name }}-{{ item }}.yml"
  with_items: "{{ files }}"
  when: files is defined

- name: "Generate Kubernetes {{ file }} files using prefix {{ prefix }}"
  template:
    src: "../templates/{{ template }}-{{ file }}.yml"
    dest: "{{ yamls }}/{{ prefix }}-{{ item[name.prop] }}-{{ file }}.yml"
  with_items: "{{ with_list }}" 
  when: with_list is defined



